package com.lifeos.enums;

public enum TimelineEventType {
	USER_CREATED,
	WORKSPACE_CREATED,
	PARTY_CREATED,
	DOCUMENT_UPLOADED,
	TASK_CREATED,
	INVESTMENT_ADDED,
	PAYMENT_RECEIVED,
	CERTIFICATION_COMPLETED,
	MEDICINE_ADDED,
	NOTE_CREATED
}
